services:
  compiler-interface:
    build:
      context: ./CompilerInterface/
      dockerfile: ./Dockerfile
    environment:
      - GIT_SSH_COMMAND=ssh -i /root/.ssh/id_rsa -o UserKnownHostsFile=/root/.ssh/known_hosts
    develop:
      watch:
        - action: rebuild
          path: ./CompilerInterface/
